---
services:
  dozzle:
    container_name: ${PLATFORM_PROJECT_NAME:?}-dozzle
    ports: !override
      - "${DOZZLE_HOST_PORT:?}:8080"
  socket-proxy:
    container_name: ${PLATFORM_PROJECT_NAME:?}-dozzle-socket-proxy
