---
services:
  alert-relay:
    container_name: ${PLATFORM_PROJECT_NAME:?}-dozzle-alert-relay
  dozzle:
    container_name: ${PLATFORM_PROJECT_NAME:?}-dozzle
  socket-proxy:
    container_name: ${PLATFORM_PROJECT_NAME:?}-dozzle-socket-proxy
