#!/bin/sh
set -eu
set +x

mac_script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
mac_repo_dir=$(CDPATH= cd -- "$mac_script_dir/../.." && pwd -P)

: "${PLATFORM_MAC_VAULT_FILE:?PLATFORM_MAC_VAULT_FILE is required}"
: "${PLATFORM_MAC_VAULT_PASSWORD_FILE:?PLATFORM_MAC_VAULT_PASSWORD_FILE is required}"
: "${PLATFORM_DOCKER_ROOT:?PLATFORM_DOCKER_ROOT is required}"
: "${PLATFORM_MEDIA_ROOT:?PLATFORM_MEDIA_ROOT is required}"
: "${PLATFORM_REPORT_ROOT:?PLATFORM_REPORT_ROOT is required}"
: "${PLATFORM_CONTRACT_SANDBOX_ROOT:?PLATFORM_CONTRACT_SANDBOX_ROOT is required}"
: "${PLATFORM_CONTRACT_SANDBOX_OWNER_UID:?PLATFORM_CONTRACT_SANDBOX_OWNER_UID is required}"
: "${PLATFORM_TINYMEDIAMANAGER_REPORT_ROOT:?PLATFORM_TINYMEDIAMANAGER_REPORT_ROOT is required}"
: "${PLATFORM_COMPOSE_KIND:?PLATFORM_COMPOSE_KIND is required}"
: "${PLATFORM_PROJECT_NAME:?PLATFORM_PROJECT_NAME is required}"
: "${PLATFORM_TINYMEDIAMANAGER_WEB_PORT:?PLATFORM_TINYMEDIAMANAGER_WEB_PORT is required}"
: "${PLATFORM_TINYMEDIAMANAGER_API_PORT:?PLATFORM_TINYMEDIAMANAGER_API_PORT is required}"
case ${1-} in
  seed-retirement-fixture|assert-retired) ;;
  *)
    printf '%s\n' 'usage: run-tinymediamanager-contract.sh seed-retirement-fixture|assert-retired' >&2
    exit 2
    ;;
esac
case ${PLATFORM_PROOF_PLATFORM:-mac} in
  integration) PLATFORM_TINYMEDIAMANAGER_CONTAINER=tinymediamanager ;;
  mac) PLATFORM_TINYMEDIAMANAGER_CONTAINER=$PLATFORM_PROJECT_NAME-tinymediamanager ;;
  *) exit 1 ;;
esac
export PLATFORM_TINYMEDIAMANAGER_CONTAINER

PLATFORM_CONTRACT_VAULT_FILE=$PLATFORM_MAC_VAULT_FILE \
PLATFORM_CONTRACT_VAULT_PASSWORD_FILE=$PLATFORM_MAC_VAULT_PASSWORD_FILE \
PLATFORM_CONTRACT_REPO_DIR=$mac_repo_dir \
PLATFORM_REPORT_ROOT=$PLATFORM_TINYMEDIAMANAGER_REPORT_ROOT \
  exec "$mac_repo_dir/tests/contracts/tinymediamanager.sh" "$@"
