#!/bin/sh
set -eu
set +x

mac_script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
mac_repo_dir=$(CDPATH= cd -- "$mac_script_dir/../.." && pwd -P)
. "$mac_repo_dir/tests/contracts/legacy-fixture-paths.sh"
legacy_fixture_unset_controls

: "${PLATFORM_MAC_VAULT_FILE:?PLATFORM_MAC_VAULT_FILE is required}"
: "${PLATFORM_MAC_VAULT_PASSWORD_FILE:?PLATFORM_MAC_VAULT_PASSWORD_FILE is required}"
: "${PLATFORM_DOCKER_ROOT:?PLATFORM_DOCKER_ROOT is required}"
: "${PLATFORM_MEDIA_ROOT:?PLATFORM_MEDIA_ROOT is required}"
: "${PLATFORM_REPORT_ROOT:?PLATFORM_REPORT_ROOT is required}"
: "${PLATFORM_PROJECT_NAME:?PLATFORM_PROJECT_NAME is required}"
: "${PLATFORM_IMMICH_PORT:?PLATFORM_IMMICH_PORT is required}"

PLATFORM_CONTRACT_VAULT_FILE=$PLATFORM_MAC_VAULT_FILE
PLATFORM_CONTRACT_VAULT_PASSWORD_FILE=$PLATFORM_MAC_VAULT_PASSWORD_FILE
case ${PLATFORM_PROOF_PLATFORM:-mac} in
  integration)
    PLATFORM_IMMICH_SERVER_CONTAINER=immich_server
    PLATFORM_IMMICH_MACHINE_LEARNING_CONTAINER=immich_machine_learning
    PLATFORM_IMMICH_REDIS_CONTAINER=immich_redis
    PLATFORM_IMMICH_POSTGRES_CONTAINER=immich_postgres
    ;;
  mac)
    PLATFORM_IMMICH_SERVER_CONTAINER=$PLATFORM_PROJECT_NAME-immich-server
    PLATFORM_IMMICH_MACHINE_LEARNING_CONTAINER=$PLATFORM_PROJECT_NAME-immich-machine-learning
    PLATFORM_IMMICH_REDIS_CONTAINER=$PLATFORM_PROJECT_NAME-immich-redis
    PLATFORM_IMMICH_POSTGRES_CONTAINER=$PLATFORM_PROJECT_NAME-immich-postgres
    ;;
  *) exit 1 ;;
esac
export PLATFORM_IMMICH_SERVER_CONTAINER PLATFORM_IMMICH_MACHINE_LEARNING_CONTAINER
export PLATFORM_IMMICH_REDIS_CONTAINER PLATFORM_IMMICH_POSTGRES_CONTAINER
export PLATFORM_CONTRACT_VAULT_FILE PLATFORM_CONTRACT_VAULT_PASSWORD_FILE
exec "$mac_repo_dir/tests/contracts/immich.sh" --platform mac "$@"
