---
services:
  audiobookshelf:
    container_name: ${PLATFORM_PROJECT_NAME:?}-audiobookshelf
    ports: !override
      - "${AUDIOBOOKSHELF_HOST_PORT:?}:80"
    volumes:
      - ${PLATFORM_DOCKER_ROOT:?}/audiobookshelf/backups:/metadata/backups
