---
x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:2.36.0@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e
    cpuset: ${PLATFORM_CONTAINER_CPUSET:?}
    cpus: 1.5
    labels:
      dev.dozzle.name: audiobookshelf
    user: "${NAS_UID:?}:${NAS_GID:?}"
    ports:
      - "13378:80"
    volumes:
      - ${AUDIOBOOKSHELF_CONFIG_PATH:?}:/config
      - ${AUDIOBOOKSHELF_METADATA_PATH:?}:/metadata
      - ${AUDIOBOOKSHELF_MEDIA_PATH:?}:/audiobooks:ro
      - ${AUDIOBOOKSHELF_BACKUP_PATH:?}:/metadata/backups
    environment:
      TZ: ${TZ:?}
    networks:
      - default
      - media-control
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, http://localhost:80/healthcheck]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging: *default-logging

networks:
  default: {}
  media-control:
    external: true
    name: ${PLATFORM_MEDIA_NETWORK:?}
