#!/usr/bin/env python3
"""Behavior tests for Configarr materialized profile-tree identities."""

from __future__ import annotations

import importlib.util
import pathlib

from ansible.errors import AnsibleFilterError


ROOT = pathlib.Path(__file__).resolve().parents[1]
PLUGIN_PATH = ROOT / "filter_plugins" / "acquisition_relationships.py"


def load_plugin():
    spec = importlib.util.spec_from_file_location(
        "acquisition_relationships", PLUGIN_PATH
    )
    if spec is None or spec.loader is None:
        raise AssertionError("acquisition relationship filter cannot be imported")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def require_rejected(items, label: str) -> None:
    try:
        profile_item_ids(items, "Configarr test profile items")
    except AnsibleFilterError:
        return
    raise AssertionError(f"accepted unsafe profile-tree identity: {label}")


def require_tree_rejected(items, label: str, expected_message: str | None = None) -> None:
    try:
        profile_tree(items, f"Configarr test {label}")
    except AnsibleFilterError as error:
        if expected_message is not None:
            assert expected_message in str(error), str(error)
        return
    raise AssertionError(f"accepted unsafe complete profile tree: {label}")


plugin = load_plugin()
profile_item_ids = plugin._configarr_profile_item_ids
profile_tree = plugin._configarr_profile_tree

valid_items = [
    {
        "id": 1001,
        "name": "WEB 1080p",
        "allowed": True,
        "items": [
            {
                "quality": {"id": 3, "name": "WEBDL-1080p"},
                "allowed": True,
                "items": [],
            },
            {
                "quality": {"id": 15, "name": "WEBRip-1080p"},
                "allowed": True,
                "items": [],
            },
        ],
    },
    {
        "quality": {"id": 7, "name": "Bluray-1080p"},
        "allowed": True,
        "items": [],
    },
]
assert profile_item_ids(valid_items, "Configarr test profile items") == {
    "WEB 1080p": 1001,
    "WEBDL-1080p": 3,
    "WEBRip-1080p": 15,
    "Bluray-1080p": 7,
}

tree = profile_tree(valid_items, "Configarr test profile items")
assert tree["items"] == [plugin._quality_item_projection(item, "test") for item in valid_items]
assert tree["item_identities"] == [
    {"path": ["group:WEB 1080p"], "kind": "group", "name": "WEB 1080p", "id": 1001},
    {
        "path": ["group:WEB 1080p", "quality:WEBDL-1080p"],
        "kind": "quality",
        "name": "WEBDL-1080p",
        "id": 3,
    },
    {
        "path": ["group:WEB 1080p", "quality:WEBRip-1080p"],
        "kind": "quality",
        "name": "WEBRip-1080p",
        "id": 15,
    },
    {
        "path": ["quality:Bluray-1080p"],
        "kind": "quality",
        "name": "Bluray-1080p",
        "id": 7,
    },
]

changed_id_items = [dict(valid_items[1], quality=dict(valid_items[1]["quality"], id=999))]
assert profile_tree(
    [valid_items[1]], "Configarr current quality items"
)["item_identities"] != profile_tree(
    changed_id_items, "Configarr current quality items"
)["item_identities"]

colliding_items = [
    {
        "id": 1001,
        "name": "WEB 1080p",
        "allowed": True,
        "items": [
            {
                "quality": {"id": 1001, "name": "WEBDL-1080p"},
                "allowed": True,
                "items": [],
            }
        ],
    }
]
require_rejected(colliding_items, "generated group and nested quality ID collision")

# Radarr and Sonarr number the built-in "Unknown" quality 0 and it appears,
# disallowed, in every stock quality profile. A group identity is generated by
# the application and starts at 1000, so 0 stays invalid there.
unknown_quality_items = [
    {"quality": {"id": 0, "name": "Unknown"}, "allowed": False, "items": []},
    {"quality": {"id": 3, "name": "WEBDL-1080p"}, "allowed": True, "items": []},
]
assert profile_item_ids(
    unknown_quality_items, "Configarr test profile items"
) == {"Unknown": 0, "WEBDL-1080p": 3}, "rejected Radarr's Unknown quality identity"
profile_tree(unknown_quality_items, "Configarr test Unknown quality tree")

# A group must carry a child, and an empty one is refused before its identifier
# is ever examined. Give every group a child so these cases exercise the
# identifier bound itself rather than the emptiness rule.
def group_with(identifier):
    return [
        {
            "id": identifier,
            "name": "WEB 1080p",
            "allowed": True,
            "items": [
                {
                    "quality": {"id": 3, "name": "WEBDL-1080p"},
                    "allowed": True,
                    "items": [],
                }
            ],
        }
    ]


for invalid_id in [True, 0, -1, "7", 1.5]:
    require_rejected(group_with(invalid_id), f"group ID {invalid_id!r}")
    require_tree_rejected(group_with(invalid_id), f"group ID {invalid_id!r}")

for invalid_id in [True, -1, "7", 1.5]:
    invalid_quality = [
        {
            "id": 1001,
            "name": "WEB 1080p",
            "allowed": True,
            "items": [
                {
                    "quality": {"id": invalid_id, "name": "WEBDL-1080p"},
                    "allowed": True,
                    "items": [],
                }
            ],
        }
    ]
    require_rejected(invalid_quality, f"nested quality ID {invalid_id!r}")
    require_tree_rejected(invalid_quality, f"nested quality ID {invalid_id!r}")

deep_items = [
    {"id": 2000, "name": "level-1", "allowed": True, "items": []}
]
cursor = deep_items[0]
for depth in range(2, 18):
    child = {"id": 2000 + depth, "name": f"level-{depth}", "allowed": True, "items": []}
    cursor["items"] = [child]
    cursor = child
require_tree_rejected(deep_items, "over-depth tree", "maximum depth 16")

wide_items = [
    {
        "quality": {"id": index + 1, "name": f"quality-{index + 1}"},
        "allowed": True,
        "items": [],
    }
    for index in range(513)
]
require_tree_rejected(wide_items, "over-count tree", "maximum node count 512")

valid_declarations = plugin.acquisition_bazarr_declarations(
    ["en"],
    [{"name": "provider_name", "settings": {"settings-provider_name-api_key": "secret"}}],
)
assert valid_declarations["provider_names"] == ["provider_name"]
for declared, expected in [
    (True, "true"),
    (False, "false"),
    (" TRUE ", "true"),
    (" false ", "false"),
]:
    boolean_declarations = plugin.acquisition_bazarr_declarations(
        ["en"],
        [{"name": "provider_name", "settings": {"settings-provider_name-enabled": declared}}],
    )
    assert boolean_declarations["provider_bodies"]["provider_name"][
        "settings-provider_name-enabled"
    ] == expected
    assert boolean_declarations["provider_settings"]["provider_name"]["enabled"] is (
        expected == "true"
    )
non_boolean_declarations = plugin.acquisition_bazarr_declarations(
    ["en"],
    [{"name": "provider_name", "settings": {"settings-provider_name-label": " truth "}}],
)
assert non_boolean_declarations["provider_bodies"]["provider_name"][
    "settings-provider_name-label"
] == " truth "
assert non_boolean_declarations["provider_settings"]["provider_name"]["label"] == " truth "

nullable_quality_group = dict(valid_items[0], quality=None)
assert profile_tree(
    [nullable_quality_group], "Configarr nullable group discriminator"
)["items"][0]["kind"] == "group"
for invalid_quality_value in ["corrupt", True, [], 7]:
    malformed_item = dict(valid_items[0], quality=invalid_quality_value)
    require_tree_rejected(
        [malformed_item], f"non-mapping quality {invalid_quality_value!r}"
    )
for label, providers in {
    "hyphenated provider": [
        {"name": "provider-name", "settings": {"settings-provider-name-api_key": "secret"}}
    ],
    "hyphenated setting suffix": [
        {"name": "provider_name", "settings": {"settings-provider_name-api-key": "secret"}}
    ],
}.items():
    try:
        plugin.acquisition_bazarr_declarations(["en"], providers)
    except AnsibleFilterError:
        continue
    raise AssertionError(f"accepted ambiguous Bazarr {label}")

print("Configarr materialized profile-tree identity behavior holds")
