---
argument_specs:
  main:
    short_description: Deploy Komga and converge its administrator and comic library
    options:
      platform_compose_kind:
        type: str
        required: true
      platform_project_name:
        type: str
        required: false
      komga_port:
        type: int
        required: false
      komga_health_retries:
        type: int
        required: false
      komga_health_delay:
        type: int
        required: false
      komga_library_name:
        type: str
        required: false
      komga_library_root:
        type: str
        required: false
      komga_library_settings:
        type: dict
        required: false
      vault_komga_admin_email:
        type: str
        required: true
      vault_komga_admin_password:
        type: str
        required: true
